### ISSUE TITLE
Some pointers

### ISSUE THREAD

**Issue by Mahiuha** [achrafelkhnissi/alx-checker#3]
How are you achraf? great job with the checker, I was going through your code and I would suggest perhaps instead of using exit to terminate the program, how about throwing exceptions and catching them in main to terminate the program, also how about using default member initialization to initialize member variables instead of using the constructor body? 

Otherwise it's a wonderful job you're doing, keep it up.

**Comment by achrafelkhnissi** [comment]
Thank you for your suggestions! I appreciate your feedback. The exit statements are just for debugging purposes, as I need the program to exit when encountering an error, I already have a few exception since i'm planning to reform my code once everything is working as intended. As for default member initialization, that's a good point, and I'll make sure to use it in my future code. Thanks again for taking the time to go through my code and giving me your suggestions!
