### ISSUE TITLE
encountering errors with the `declare` command

### ISSUE THREAD

**Issue by Mahiuha** [achrafelkhnissi/alx-checker#5]
How are you, El khnissi? it's me again, to fix the above error, for people who have shell environment that do not support the `declare` command or not having the necessary permissions to run it then they should try using:
```
sudo bash -c "$(curl -fsSL https://raw.githubusercontent.com/achrafelkhnissi/alx-checker/main/install.sh)"
```
Thankyou.

**Comment by achrafelkhnissi** [comment]
I'm doing well, thank you. I appreciate your suggestion I've made the necessary changes as well as fixing the colors not being displayed. Not I'm just working on [alx-low_level_programming](https://github.com/achrafelkhnissi/alx-low_level_programming) repo so that everything ready so I can release the beta version! hope you try it and report any bug or issue or any suggestion.
